/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBarSearch: typeof import('./resources/js/@core/components/AppBarSearch.vue')['default']
    AppDateTimePicker: typeof import('./resources/js/@core/components/AppDateTimePicker.vue')['default']
    CustomizerSection: typeof import('./resources/js/@core/components/CustomizerSection.vue')['default']
    I18n: typeof import('./resources/js/@core/components/I18n.vue')['default']
    Notifications: typeof import('./resources/js/@core/components/Notifications.vue')['default']
    Shortcuts: typeof import('./resources/js/@core/components/Shortcuts.vue')['default']
    TheCustomizer: typeof import('./resources/js/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
  }
}
